// Shared ASUS product catalog used by search-products, get-product-details,
// browse-products-by-series, compare-products and manage-cart.
//
// TODO: Replace CATALOG with a real API/PIM call. Suggested endpoint pattern:
//   GET ${process.env.API_BASE_URL}/products
// Environment variables to configure in .env and app.config.yaml `inputs`:
//   API_BASE_URL, API_KEY
// Until then this is a realistic, hand-authored dataset spanning ASUS's
// consumer lines so search/compare/cart have enough breadth to answer
// queries like "gaming laptop under $1200".

// Order matters — used to compare "at least this tier" GPU filters.
const GPU_TIERS = ['integrated', 'entry', 'mid', 'high', 'enthusiast'];

const CATALOG = [
  // ---- Zenbook (premium ultraportable / productivity) ----
  {
    id: 'zenbook-duo-ux8407',
    name: 'ASUS Zenbook DUO (UX8407)',
    brand_line: 'zenbook',
    series: 'Zenbook Duo',
    category: 'Zenbook Duo',
    description: 'Dual 3K Lumina Pro OLED laptop with Intel Core Ultra Series 3, 18+ hr battery, and durable Ceraluminum chassis.',
    highlights: ['Dual 14" 3K OLED displays', 'Detachable backlit keyboard', '18+ hour battery life'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/cee1353c-a974-4436-9235-ce4443f58285/w800/fwebp',
    price_usd: 1999,
    cpu: 'Intel Core Ultra 9 285H',
    gpu: 'Intel Arc Graphics (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 14,
    battery_hours: 18,
    weight_kg: 1.65,
    rating: 4.6,
    review_count: 128,
    in_stock: true,
    use_cases: ['productivity', 'creator', 'business'],
  },
  {
    id: 'zenbook-14-ux3480',
    name: 'ASUS Zenbook 14 (UX3480); Copilot+ PC',
    brand_line: 'zenbook',
    series: 'Zenbook',
    category: 'Zenbook',
    description: 'Lightweight 14-inch Copilot+ PC in the Zenbook family.',
    highlights: ['Copilot+ PC AI features', 'All-day battery', 'Ultra-light magnesium-alloy body'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/696b867d-2d95-4af2-b2d4-0ad7799ef495/w800/fwebp',
    price_usd: 1299,
    cpu: 'Intel Core Ultra 7 258V',
    gpu: 'Intel Arc Graphics (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 16,
    storage_gb: 512,
    screen_size_in: 14,
    battery_hours: 20,
    weight_kg: 1.2,
    rating: 4.5,
    review_count: 96,
    in_stock: true,
    use_cases: ['productivity', 'student'],
  },
  {
    id: 'zenbook-a16-ux3607',
    name: 'ASUS Zenbook A16 (UX3607); Copilot+ PC',
    brand_line: 'zenbook',
    series: 'Zenbook A',
    category: 'Zenbook A',
    description: '16-inch Zenbook A-series Copilot+ PC.',
    highlights: ['Ceraluminum chassis under 1.5kg', 'Copilot+ PC AI features', '16" 3K OLED'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/ec3e3399-c34a-4ed9-be76-c9be1ac1ca6e/w800/fwebp',
    price_usd: 1499,
    cpu: 'AMD Ryzen AI 9 HX 370',
    gpu: 'AMD Radeon 890M (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 16,
    battery_hours: 16,
    weight_kg: 1.5,
    rating: 4.7,
    review_count: 74,
    in_stock: true,
    use_cases: ['productivity', 'creator'],
  },
  {
    id: 'zenbook-a14-ux3407',
    name: 'ASUS Zenbook A14 (UX3407); Copilot+ PC',
    brand_line: 'zenbook',
    series: 'Zenbook A',
    category: 'Zenbook A',
    description: 'Ultralight 14-inch Zenbook A-series Copilot+ PC.',
    highlights: ['Under 1kg', 'Copilot+ PC AI features', '14" OLED'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/daf7ed78-fcec-4f54-82a6-db3204fdece3/w800/fwebp',
    price_usd: 1199,
    cpu: 'AMD Ryzen AI 7 350',
    gpu: 'AMD Radeon 860M (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 16,
    storage_gb: 512,
    screen_size_in: 14,
    battery_hours: 17,
    weight_kg: 0.98,
    rating: 4.6,
    review_count: 61,
    in_stock: true,
    use_cases: ['student', 'travel', 'productivity'],
  },
  {
    id: 'zenbook-s16-ux5606',
    name: 'ASUS Zenbook S16 (UX5606); Copilot+ PC',
    brand_line: 'zenbook',
    series: 'Zenbook S',
    category: 'Zenbook S',
    description: 'Premium 16-inch Zenbook S-series Copilot+ PC.',
    highlights: ['16" 3K OLED 120Hz', 'Ceraluminum chassis', 'Copilot+ PC AI features'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/8264ddf7-ccc7-4b11-b18d-360f92049814/w800/fwebp',
    price_usd: 1599,
    cpu: 'Intel Core Ultra 9 285H',
    gpu: 'Intel Arc Graphics (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 16,
    battery_hours: 15,
    weight_kg: 1.5,
    rating: 4.8,
    review_count: 83,
    in_stock: true,
    use_cases: ['creator', 'productivity'],
  },
  {
    id: 'zenbook-s14-ux5406',
    name: 'ASUS Zenbook S14 (UX5406); Copilot+ PC',
    brand_line: 'zenbook',
    series: 'Zenbook S',
    category: 'Zenbook S',
    description: 'Premium 14-inch Zenbook S-series Copilot+ PC.',
    highlights: ['14" 3K OLED', 'Under 1.2kg', 'Copilot+ PC AI features'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/827c5809-1d54-487a-aad4-9b5c0aee3fb8/w800/fwebp',
    price_usd: 1399,
    cpu: 'Intel Core Ultra 7 258V',
    gpu: 'Intel Arc Graphics (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 16,
    storage_gb: 1024,
    screen_size_in: 14,
    battery_hours: 17,
    weight_kg: 1.2,
    rating: 4.7,
    review_count: 69,
    in_stock: true,
    use_cases: ['productivity', 'travel'],
  },
  {
    id: 'zenbook-14-um3406za',
    name: 'ASUS Zenbook 14 (UM3406ZA)',
    brand_line: 'zenbook',
    series: 'Zenbook',
    category: 'Zenbook',
    description: '14-inch Zenbook laptop.',
    highlights: ['14" display', 'All-day battery', 'Value Zenbook pick'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/1474e646-c89a-484b-b052-e3e2e46a1e5a/w800/fwebp',
    price_usd: 899,
    cpu: 'AMD Ryzen 7 7735U',
    gpu: 'AMD Radeon 660M (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 16,
    storage_gb: 512,
    screen_size_in: 14,
    battery_hours: 14,
    weight_kg: 1.3,
    rating: 4.3,
    review_count: 142,
    in_stock: true,
    use_cases: ['student', 'budget', 'productivity'],
  },

  // ---- ROG (Republic of Gamers — high-performance gaming) ----
  {
    id: 'rog-zephyrus-g14-ga403',
    name: 'ROG Zephyrus G14 (GA403)',
    brand_line: 'rog',
    series: 'ROG Zephyrus',
    category: 'ROG Zephyrus',
    description: 'Ultra-slim 14" gaming laptop that pairs serious RTX performance with an AniMe Matrix lid.',
    highlights: ['14" QHD+ 165Hz', 'RTX 4070', 'AniMe Matrix display'],
    image_url: null,
    price_usd: 1799,
    cpu: 'AMD Ryzen 9 8945HS',
    gpu: 'NVIDIA RTX 4070',
    gpu_tier: 'high',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 14,
    battery_hours: 10,
    weight_kg: 1.5,
    rating: 4.7,
    review_count: 58,
    in_stock: true,
    use_cases: ['gaming', 'creator'],
  },
  {
    id: 'rog-zephyrus-g16-gu605',
    name: 'ROG Zephyrus G16 (GU605)',
    brand_line: 'rog',
    series: 'ROG Zephyrus',
    category: 'ROG Zephyrus',
    description: 'Flagship 16" gaming laptop with a 240Hz OLED panel and enthusiast-grade RTX 4080 graphics.',
    highlights: ['16" OLED 240Hz', 'RTX 4080', 'CNC-milled aluminum chassis'],
    image_url: null,
    price_usd: 2199,
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'NVIDIA RTX 4080',
    gpu_tier: 'enthusiast',
    ram_gb: 32,
    storage_gb: 2048,
    screen_size_in: 16,
    battery_hours: 9,
    weight_kg: 1.85,
    rating: 4.8,
    review_count: 41,
    in_stock: true,
    use_cases: ['gaming', 'creator'],
  },
  {
    id: 'rog-strix-g16-g614',
    name: 'ROG Strix G16 (G614)',
    brand_line: 'rog',
    series: 'ROG Strix',
    category: 'ROG Strix',
    description: 'Mainstream 16" gaming laptop built for fast 1080p/1440p frame rates at a more approachable price.',
    highlights: ['16" 165Hz', 'RTX 4060', 'ROG Intelligent Cooling'],
    image_url: null,
    price_usd: 1499,
    cpu: 'Intel Core i7-14650HX',
    gpu: 'NVIDIA RTX 4060',
    gpu_tier: 'mid',
    ram_gb: 16,
    storage_gb: 512,
    screen_size_in: 16,
    battery_hours: 8,
    weight_kg: 2.5,
    rating: 4.5,
    review_count: 112,
    in_stock: true,
    use_cases: ['gaming'],
  },
  {
    id: 'rog-strix-scar18-g834',
    name: 'ROG Strix SCAR 18 (G834)',
    brand_line: 'rog',
    series: 'ROG Strix',
    category: 'ROG Strix',
    description: 'Desktop-replacement esports flagship with an 18" Mini LED display and the fastest mobile RTX GPU.',
    highlights: ['18" Mini LED 240Hz', 'RTX 4090', 'Per-key RGB keyboard'],
    image_url: null,
    price_usd: 2999,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 4090',
    gpu_tier: 'enthusiast',
    ram_gb: 64,
    storage_gb: 2048,
    screen_size_in: 18,
    battery_hours: 6,
    weight_kg: 3.1,
    rating: 4.9,
    review_count: 27,
    in_stock: true,
    use_cases: ['gaming'],
  },

  // ---- TUF Gaming (durable, value gaming) ----
  {
    id: 'tuf-gaming-a15-fa507',
    name: 'TUF Gaming A15 (FA507)',
    brand_line: 'tuf',
    series: 'TUF Gaming',
    category: 'TUF Gaming',
    description: 'Military-grade durable gaming laptop that keeps entry pricing without giving up 144Hz smoothness.',
    highlights: ['15.6" 144Hz', 'RTX 4050', 'MIL-STD-810H durability'],
    image_url: null,
    price_usd: 999,
    cpu: 'AMD Ryzen 7 7735HS',
    gpu: 'NVIDIA RTX 4050',
    gpu_tier: 'entry',
    ram_gb: 16,
    storage_gb: 512,
    screen_size_in: 15.6,
    battery_hours: 7,
    weight_kg: 2.2,
    rating: 4.3,
    review_count: 203,
    in_stock: true,
    use_cases: ['gaming', 'budget'],
  },
  {
    id: 'tuf-gaming-f15-fx507',
    name: 'TUF Gaming F15 (FX507)',
    brand_line: 'tuf',
    series: 'TUF Gaming',
    category: 'TUF Gaming',
    description: 'A step up in the TUF line with a faster RTX 4060 and more storage headroom.',
    highlights: ['15.6" 144Hz', 'RTX 4060', 'Self-Cleaning Cooling'],
    image_url: null,
    price_usd: 1149,
    cpu: 'Intel Core i7-13620H',
    gpu: 'NVIDIA RTX 4060',
    gpu_tier: 'mid',
    ram_gb: 16,
    storage_gb: 1024,
    screen_size_in: 15.6,
    battery_hours: 7,
    weight_kg: 2.2,
    rating: 4.4,
    review_count: 88,
    in_stock: true,
    use_cases: ['gaming'],
  },

  // ---- Vivobook (mainstream / colorful everyday laptops) ----
  {
    id: 'vivobook-s15-s5507',
    name: 'Vivobook S15 (S5507); Copilot+ PC',
    brand_line: 'vivobook',
    series: 'Vivobook S',
    category: 'Vivobook S',
    description: 'Everyday 15.6" OLED laptop with Copilot+ PC AI features for school and work.',
    highlights: ['15.6" OLED', 'Copilot+ PC AI features', 'Lightweight for its size'],
    image_url: null,
    price_usd: 999,
    cpu: 'Intel Core Ultra 7 258V',
    gpu: 'Intel Arc Graphics (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 16,
    storage_gb: 512,
    screen_size_in: 15.6,
    battery_hours: 14,
    weight_kg: 1.4,
    rating: 4.4,
    review_count: 97,
    in_stock: true,
    use_cases: ['student', 'productivity'],
  },
  {
    id: 'vivobook-pro15-n6506',
    name: 'Vivobook Pro 15 (N6506)',
    brand_line: 'vivobook',
    series: 'Vivobook Pro',
    category: 'Vivobook Pro',
    description: 'Creator-leaning Vivobook with a discrete RTX GPU for light gaming and video editing.',
    highlights: ['15.6" OLED', 'RTX 4050', 'Great value for content creation'],
    image_url: null,
    price_usd: 1099,
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'NVIDIA RTX 4050',
    gpu_tier: 'entry',
    ram_gb: 16,
    storage_gb: 1024,
    screen_size_in: 15.6,
    battery_hours: 10,
    weight_kg: 1.7,
    rating: 4.3,
    review_count: 54,
    in_stock: true,
    use_cases: ['creator', 'gaming', 'student'],
  },

  // ---- ProArt (creator / studio) ----
  {
    id: 'proart-studiobook16-h7604',
    name: 'ProArt Studiobook 16 (H7604)',
    brand_line: 'proart',
    series: 'ProArt Studiobook',
    category: 'ProArt Studiobook',
    description: 'Color-calibrated 4K OLED studio laptop for video editors, 3D artists and designers.',
    highlights: ['16" 4K OLED, Pantone Validated', 'RTX 4070', 'Dial-controller for creative apps'],
    image_url: null,
    price_usd: 2499,
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'NVIDIA RTX 4070',
    gpu_tier: 'high',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 16,
    battery_hours: 9,
    weight_kg: 2.4,
    rating: 4.8,
    review_count: 33,
    in_stock: true,
    use_cases: ['creator', 'professional'],
  },
  {
    id: 'proart-p16-h7606',
    name: 'ProArt P16 (H7606)',
    brand_line: 'proart',
    series: 'ProArt Studiobook',
    category: 'ProArt Studiobook',
    description: 'Touch-enabled OLED creator laptop with a built-in dial for fine-tuned adjustments in creative apps.',
    highlights: ['16" OLED touch', 'RTX 4060', 'ProArt Creator Hub software'],
    image_url: null,
    price_usd: 1899,
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'NVIDIA RTX 4060',
    gpu_tier: 'mid',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 16,
    battery_hours: 9,
    weight_kg: 2.2,
    rating: 4.6,
    review_count: 22,
    in_stock: true,
    use_cases: ['creator'],
  },
];

// Cross-sell / upsell accessories — separate from the laptop CATALOG so
// search-products/browse-products-by-series (which only ever browse
// laptops) don't accidentally surface a mouse or a monitor. Used by
// get-recommendations and addable to the cart like any laptop.
const ACCESSORIES = [
  {
    id: 'rog-gladius-iii-mouse',
    name: 'ROG Gladius III Wireless Mouse',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Gaming Mouse',
    description: 'Lightweight wireless gaming mouse with swappable switches and Aura Sync RGB.',
    highlights: ['79g ultralight design', 'Hot-swappable switches', '2.4GHz wireless + Bluetooth'],
    image_url: null,
    price_usd: 99,
    rating: 4.7,
    review_count: 340,
    in_stock: true,
    use_cases: ['gaming'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'asus-dual-usb-c-dock',
    name: 'ASUS Dual USB-C Docking Station',
    brand_line: 'zenbook',
    series: 'ASUS Accessories',
    category: 'Docking Station',
    description: 'One-cable 4K dual-monitor dock with 100W power delivery — ideal for ultraportables.',
    highlights: ['Dual 4K@60Hz output', '100W USB-C power delivery', 'Single-cable desk setup'],
    image_url: null,
    price_usd: 149,
    rating: 4.5,
    review_count: 212,
    in_stock: true,
    use_cases: ['productivity', 'business', 'creator'],
    compatible_brand_lines: ['zenbook', 'vivobook', 'proart'],
    is_accessory: true,
  },
  {
    id: 'asus-neoprene-sleeve-14',
    name: 'ASUS Neoprene Sleeve 14"',
    brand_line: 'zenbook',
    series: 'ASUS Accessories',
    category: 'Sleeve',
    description: 'Slim protective sleeve for 14-inch laptops, water-resistant neoprene.',
    highlights: ['Water-resistant exterior', 'Soft interior lining', 'Fits most 14" laptops'],
    image_url: null,
    price_usd: 29,
    rating: 4.4,
    review_count: 501,
    in_stock: true,
    use_cases: ['travel', 'student', 'productivity'],
    compatible_brand_lines: ['zenbook', 'vivobook'],
    is_accessory: true,
  },
  {
    id: 'rog-strix-xg27-monitor',
    name: 'ROG Strix XG27AQ 27" Gaming Monitor',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Monitor',
    description: '27" QHD 170Hz IPS gaming monitor with G-SYNC compatibility.',
    highlights: ['170Hz QHD IPS panel', 'G-SYNC Compatible', 'HDR400'],
    image_url: null,
    price_usd: 399,
    rating: 4.8,
    review_count: 150,
    in_stock: true,
    use_cases: ['gaming'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'proart-pa279-monitor',
    name: 'ProArt Display PA279CRV 27" 4K Monitor',
    brand_line: 'proart',
    series: 'ProArt Accessories',
    category: 'Monitor',
    description: 'Factory-calibrated 4K HDR monitor for color-critical creative work.',
    highlights: ['Factory color calibration', '4K UHD, 98% DCI-P3', 'Built-in colorimeter support'],
    image_url: null,
    price_usd: 599,
    rating: 4.8,
    review_count: 87,
    in_stock: true,
    use_cases: ['creator', 'professional'],
    compatible_brand_lines: ['proart', 'zenbook'],
    is_accessory: true,
  },
  {
    id: 'asus-portable-ssd-1tb',
    name: 'ASUS 1TB Portable SSD',
    brand_line: 'vivobook',
    series: 'ASUS Accessories',
    category: 'Storage',
    description: 'Pocket-sized 1TB USB-C SSD with up to 1050MB/s transfer speeds.',
    highlights: ['1050MB/s transfer speeds', 'Pocket-sized aluminum body', 'USB-C, backward compatible'],
    image_url: null,
    price_usd: 89,
    rating: 4.6,
    review_count: 275,
    in_stock: true,
    use_cases: ['creator', 'student', 'productivity', 'gaming'],
    compatible_brand_lines: ['zenbook', 'rog', 'tuf', 'vivobook', 'proart'],
    is_accessory: true,
  },
];

// Combined index used for lookups (get-product-details, manage-cart,
// compare-products, get-recommendations) so accessories are addressable
// the same way laptops are. Laptop-only browsing (search-products,
// browse-products-by-series) intentionally keeps using CATALOG alone.
const ALL_ITEMS = [...CATALOG, ...ACCESSORIES];

/**
 * Fallback color swatch per brand line, used by widgets when a product has
 * no image_url. Kept here (not just in the EDS repo) so the structuredContent
 * payload can optionally carry it for hosts that don't run the EDS widget.
 */
const BRAND_FALLBACK_COLOR = {
  zenbook: '#0B3D91',
  rog: '#FF0000',
  tuf: '#FFA400',
  vivobook: '#7B2FF7',
  proart: '#FF6B00',
};

/**
 * TODO: Replace with a real product-page/cart deep link once available
 * (ASUS store PDP URL or Adobe Commerce cart-add endpoint + auth pattern).
 */
function buyUrl(product) {
  return `https://www.asus.com/search/?q=${encodeURIComponent(product.name)}`;
}

/** Trims a catalog record down to the fields widgets actually render. */
function toCard(product) {
  return {
    id: product.id,
    name: product.name,
    description: product.description,
    image_url: product.image_url,
    category: product.category,
    brand_line: product.brand_line,
    price_usd: product.price_usd,
    cpu: product.cpu,
    gpu: product.gpu,
    gpu_tier: product.gpu_tier,
    ram_gb: product.ram_gb,
    storage_gb: product.storage_gb,
    screen_size_in: product.screen_size_in,
    weight_kg: product.weight_kg,
    battery_hours: product.battery_hours,
    rating: product.rating,
    review_count: product.review_count,
    in_stock: product.in_stock,
    use_cases: product.use_cases,
    highlights: product.highlights,
    fallback_color: BRAND_FALLBACK_COLOR[product.brand_line] || '#1a1a1a',
    buy_url: buyUrl(product),
    is_accessory: !!product.is_accessory,
  };
}

/**
 * Resolves a single product OR accessory by id (exact) or name (exact,
 * then partial). Used by get-product-details, compare-products, the cart
 * actions, and get-recommendations.
 */
function resolveProduct({ product_id, product_name } = {}) {
  if (product_id) {
    const byId = ALL_ITEMS.find((p) => p.id === product_id);
    if (byId) return byId;
  }
  if (product_name && typeof product_name === 'string' && product_name.trim()) {
    const query = product_name.trim().toLowerCase();
    const exact = ALL_ITEMS.find((p) => p.name.toLowerCase() === query);
    if (exact) return exact;
    const partial = ALL_ITEMS.find((p) => p.name.toLowerCase().includes(query));
    if (partial) return partial;
  }
  return null;
}

module.exports = {
  CATALOG,
  ACCESSORIES,
  ALL_ITEMS,
  GPU_TIERS,
  BRAND_FALLBACK_COLOR,
  toCard,
  resolveProduct,
  buyUrl,
};
