// Shared ASUS product catalog used by search-products, get-product-details,
// browse-products-by-series, compare-products and manage-cart.
//
// REFRESHED July 2026: every laptop below is a real, currently-sold ASUS
// model, sourced directly from asus.com / eshop.asus.com product pages
// (name, price, CPU/GPU/RAM/storage/screen/weight, and a real hero image
// hosted on ASUS's own CDN). Ratings/review counts are still synthetic —
// ASUS doesn't publish aggregate review data on these pages — everything
// else is real as of the last refresh. `product_url` links straight to the
// live ASUS page for that model.
//
// SECOND RESEARCH PASS (July 2026): added 5 more laptops (ROG Flow Z13,
// TUF Gaming F16, Zenbook 14 OLED UX3405, Vivobook Pro 15 OLED N6506,
// Vivobook Go 15 E1504G) and 11 more accessories (keyboard, earbuds,
// webcam, backpack, dock, mouse, mousepad, and 4 monitors). Some of these
// prices are confirmed live prices at research time; others are
// retailer-sourced or reasonable estimates where ASUS doesn't show a live
// price — see the inline price comments on each new item below.
//
// TODO: Replace this hand-refreshed dataset with a real API/PIM call once
// available. Suggested endpoint pattern:
//   GET ${process.env.API_BASE_URL}/products
// Environment variables to configure in .env and app.config.yaml `inputs`:
//   API_BASE_URL, API_KEY
// Until then, re-run the research pass periodically (prices/specs/images
// above) to keep this from going stale — ASUS refreshes these lines often.

// Order matters — used to compare "at least this tier" GPU filters.
const GPU_TIERS = ['integrated', 'entry', 'mid', 'high', 'enthusiast'];

const CATALOG = [
  // ---- ROG (Republic of Gamers — high-performance gaming) ----
  {
    id: 'rog-zephyrus-g14-2025',
    name: 'ROG Zephyrus G14 (2025)',
    brand_line: 'rog',
    series: 'ROG Zephyrus',
    category: 'ROG Zephyrus',
    description: 'The lightest ROG laptop ASUS has ever built — an ultra-slim 14" gaming laptop with an RTX 5080 and AI accelerators built into both CPU and GPU.',
    highlights: ['14" 3K OLED, 120Hz, ROG Nebula HDR Display', 'NVIDIA GeForce RTX 5080 Laptop GPU', 'Only 1.5kg — the lightest ROG ever made'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/BA146EC2-FF9D-4A8E-A91A-C9F864DE6BBB',
    product_url: 'https://rog.asus.com/us/laptops/rog-zephyrus/rog-zephyrus-g14-2025/',
    price_usd: 2499,
    cpu: 'AMD Ryzen AI 9 HX 370',
    gpu: 'NVIDIA GeForce RTX 5080',
    gpu_tier: 'high',
    ram_gb: 32,
    storage_gb: 2048,
    screen_size_in: 14,
    battery_hours: 10,
    weight_kg: 1.5,
    rating: 4.8,
    review_count: 64,
    in_stock: true,
    use_cases: ['gaming', 'creator'],
  },
  {
    id: 'rog-strix-scar18-2026',
    name: 'ROG Strix SCAR 18 (2026)',
    brand_line: 'rog',
    series: 'ROG Strix',
    category: 'ROG Strix',
    description: 'ASUS\'s flagship 18" desktop-replacement — the world\'s first 4K 240Hz Mini LED laptop panel, paired with the fastest mobile GPU ASUS offers and a customizable AniMe Vision lid.',
    highlights: ['18" 4K (3840x2400) Mini LED, 240Hz, Pantone Validated', 'NVIDIA GeForce RTX 5080 Laptop GPU, 16GB GDDR7', 'Customizable AniMe Vision lid display'],
    image_url: 'https://eshop.asus.com/media/catalog/product/0/e/0e90fa4926512081ca977f17d0589c9a.png',
    product_url: 'https://eshop.asus.com/us/rog/rog-strix-scar-18-2026-gaming-laptop.html',
    price_usd: 4299,
    cpu: 'Intel Core Ultra 9 290HX+',
    gpu: 'NVIDIA GeForce RTX 5080 (16GB)',
    gpu_tier: 'enthusiast',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 18,
    battery_hours: 7,
    weight_kg: 3.7,
    rating: 4.9,
    review_count: 22,
    in_stock: true,
    use_cases: ['gaming'],
  },
  {
    id: 'rog-strix-g16-2025',
    name: 'ROG Strix G16 (2025)',
    brand_line: 'rog',
    series: 'ROG Strix',
    category: 'ROG Strix',
    description: 'ASUS\'s "true next-gen gaming laptop" at a more approachable price — 16" of fast-refresh gaming with NVIDIA Advanced Optimus and RTX 50-series graphics.',
    highlights: ['16" up to 2.5K WQXGA, 240Hz', 'NVIDIA GeForce RTX 5070 Laptop GPU', 'NVIDIA Advanced Optimus'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/CB995004-F8A4-4EFC-915A-DE8C414E6F9D',
    product_url: 'https://rog.asus.com/us/laptops/rog-strix/rog-strix-g16-2025/',
    price_usd: 1399,
    cpu: 'Intel Core Ultra 9 275HX',
    gpu: 'NVIDIA GeForce RTX 5070',
    gpu_tier: 'mid',
    ram_gb: 16,
    storage_gb: 1024,
    screen_size_in: 16,
    battery_hours: 8,
    weight_kg: 2.4,
    rating: 4.5,
    review_count: 118,
    in_stock: true,
    use_cases: ['gaming'],
  },
  {
    id: 'rog-flow-z13-2025',
    name: 'ROG Flow Z13 (2025) GZ302',
    brand_line: 'rog',
    series: 'ROG Flow',
    category: 'ROG Flow',
    description: 'A 2-in-1 gaming tablet with a detachable keyboard — ASUS pairs a fast 180Hz touch display with AMD\'s unified Ryzen AI Max+ silicon for genuine desktop-class gaming in a tablet form factor.',
    highlights: ['13.4" WQXGA 180Hz touchscreen', 'AMD Ryzen AI Max+ 395 with unified memory (configurable up to 128GB)', 'Detachable backlit keyboard — full gaming laptop or standalone tablet'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/34C1E26D-F64A-4B4F-8DAC-6C168F7C90E2',
    product_url: 'https://rog.asus.com/us/laptops/rog-flow/rog-flow-z13-2025/',
    price_usd: 2099.99, // confirmed live price for the base config (128GB unified-memory config lists at $3,299.99)
    cpu: 'AMD Ryzen AI Max+ 395',
    gpu: 'AMD Radeon 8060S Graphics (unified)',
    gpu_tier: 'high',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 13.4,
    battery_hours: 9,
    weight_kg: 1.18,
    rating: 4.6,
    review_count: 47,
    in_stock: true,
    use_cases: ['gaming', 'creator', 'travel'],
  },

  // ---- TUF Gaming (durable, value gaming) ----
  {
    id: 'tuf-gaming-a16-2025',
    name: 'TUF Gaming A16 (2025)',
    brand_line: 'tuf',
    series: 'TUF Gaming',
    category: 'TUF Gaming',
    description: '"Robust Performance, Elevated Victory" — a MIL-STD-810H durable gaming laptop with 0dB Ambient Cooling and dependable RTX 50-series graphics at a value price.',
    highlights: ['16" FHD+ 165Hz, G-Sync', 'NVIDIA GeForce RTX 5060 Laptop GPU', 'MIL-STD-810H military-grade durability'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/c0b28d76-4515-4965-9982-18898fdd5208/w800',
    product_url: 'https://www.asus.com/us/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-a16-2025/',
    price_usd: 1399,
    cpu: 'AMD Ryzen 9 8940HX',
    gpu: 'NVIDIA GeForce RTX 5060',
    gpu_tier: 'entry',
    ram_gb: 16,
    storage_gb: 1024,
    screen_size_in: 16,
    battery_hours: 9,
    weight_kg: 2.2,
    rating: 4.4,
    review_count: 206,
    in_stock: true,
    use_cases: ['gaming', 'budget'],
  },
  {
    id: 'tuf-gaming-a14-2024',
    name: 'TUF Gaming A14 (2024)',
    brand_line: 'tuf',
    series: 'TUF Gaming',
    category: 'TUF Gaming',
    description: 'The smallest TUF Gaming laptop ASUS has built — "Portable Power, Maximum Impact" in a sub-1.5kg MIL-STD-810H chassis.',
    highlights: ['14" 2.5K (2560x1600) 165Hz IPS, 100% sRGB', 'NVIDIA GeForce RTX 4060 Laptop GPU', 'Only 1.46kg — smallest TUF Gaming ever built'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/8ef79421-e9c6-4c8b-8529-0e0dc2a09952/w800',
    product_url: 'https://www.asus.com/us/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-a14-2024/',
    price_usd: 1299,
    cpu: 'AMD Ryzen AI 9 HX 370',
    gpu: 'NVIDIA GeForce RTX 4060',
    gpu_tier: 'entry',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 14,
    battery_hours: 10,
    weight_kg: 1.46,
    rating: 4.5,
    review_count: 71,
    in_stock: true,
    use_cases: ['gaming', 'travel', 'budget'],
  },
  {
    id: 'tuf-gaming-f16-2026',
    name: 'TUF Gaming F16 (2026)',
    brand_line: 'tuf',
    series: 'TUF Gaming',
    category: 'TUF Gaming',
    description: 'A 16" MIL-STD-810H gaming laptop that scales up to Intel\'s top HX-series chips and RTX 50-series graphics behind a fast 2.5K 165Hz OLED panel.',
    highlights: ['16" 2.5K OLED, 165Hz', 'Up to Intel Core Ultra 9 290HX+ and NVIDIA GeForce RTX 5070', 'MIL-STD-810H military-grade durability'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/5b03a41b-4a51-4db6-9ad6-5628c01201c0/',
    product_url: 'https://www.asus.com/us/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-f16-2026/',
    price_usd: 1499.99, // estimated — not live-priced by ASUS at research time
    cpu: 'Intel Core Ultra 9 290HX+',
    gpu: 'NVIDIA GeForce RTX 5070',
    gpu_tier: 'mid',
    ram_gb: 16,
    storage_gb: 1024,
    screen_size_in: 16,
    battery_hours: 9,
    weight_kg: 2.3,
    rating: 4.4,
    review_count: 38,
    in_stock: true,
    use_cases: ['gaming'],
  },

  // ---- Zenbook (premium ultraportable / productivity — "quiet luxury") ----
  {
    id: 'zenbook-s16-um5606',
    name: 'ASUS Zenbook S16 (UM5606)',
    brand_line: 'zenbook',
    series: 'Zenbook S',
    category: 'Zenbook S',
    description: '"A statement of craftsmanship defined by its meticulous detailing" — the Zenbook S line\'s flagship, in a Ceraluminum chassis with Harman/Kardon-tuned audio.',
    highlights: ['16" 3K OLED, 120Hz, touch', 'Six Super Linear Speakers, tuned by Harman/Kardon', 'Ceraluminum chassis, 1.50kg'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/f34d32c6-c387-4d9f-a3ae-b7e22bcd8720/',
    product_url: 'https://www.asus.com/us/laptops/for-home/zenbook/asus-zenbook-s-16-um5606/',
    price_usd: 1199,
    cpu: 'AMD Ryzen AI 7 350',
    gpu: 'AMD Radeon Graphics (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 24,
    storage_gb: 1024,
    screen_size_in: 16,
    battery_hours: 18,
    weight_kg: 1.5,
    rating: 4.6,
    review_count: 133,
    in_stock: true,
    use_cases: ['productivity', 'creator', 'business'],
  },
  {
    id: 'zenbook-duo-ux8407-2026',
    name: 'ASUS Zenbook DUO (UX8407)',
    brand_line: 'zenbook',
    series: 'Zenbook Duo',
    category: 'Zenbook Duo',
    description: '"Let\'s DUO it" — the dual 14" 3K OLED screen laptop with the fastest graphics, longest battery, and next-gen AI in the Zenbook DUO line, letting you carry your complete workspace anywhere.',
    highlights: ['Dual 14" 3K OLED displays, 120Hz', 'Detachable backlit keyboard', 'Intel Core Ultra X9 388H + Intel Arc B390 graphics'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/9fe03e85-4f8e-416e-bdea-2eb8879361aa/',
    product_url: 'https://www.asus.com/us/laptops/for-home/zenbook/asus-zenbook-duo-ux8407/',
    price_usd: 2299,
    cpu: 'Intel Core Ultra X9 388H',
    gpu: 'Intel Arc B390',
    gpu_tier: 'mid',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 14,
    battery_hours: 18,
    weight_kg: 1.65,
    rating: 4.6,
    review_count: 129,
    in_stock: true,
    use_cases: ['productivity', 'creator', 'business'],
  },
  {
    id: 'zenbook-a14-ux3407-2025',
    name: 'ASUS Zenbook A14 (UX3407)',
    brand_line: 'zenbook',
    series: 'Zenbook A',
    category: 'Zenbook A',
    description: '"Unload. Unplugged. Unlimited." — ASUS\'s lightest Zenbook ever, in a full-body Ceraluminum chassis that\'s entirely life-resistant, with the longest battery life in the lineup.',
    highlights: ['Full-body Ceraluminum™ chassis, sub-1kg', '33+ hour rated battery life', 'Qualcomm Snapdragon X2 Elite (ARM, always-connected)'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/ac85e468-3f21-4773-a8e8-8c72034a5f19/',
    product_url: 'https://www.asus.com/us/laptops/for-home/zenbook/asus-zenbook-a-14-ux3407/',
    price_usd: 1099,
    cpu: 'Qualcomm Snapdragon X2 Elite',
    gpu: 'Qualcomm Adreno (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 16,
    storage_gb: 512,
    screen_size_in: 14,
    battery_hours: 33,
    weight_kg: 0.99,
    rating: 4.7,
    review_count: 58,
    in_stock: true,
    use_cases: ['student', 'travel', 'productivity'],
  },
  {
    id: 'zenbook-14-ux3405-2024',
    name: 'ASUS Zenbook 14 OLED (UX3405)',
    brand_line: 'zenbook',
    series: 'Zenbook 14',
    category: 'Zenbook 14',
    description: 'The mainstream Zenbook 14 pairs a vivid 3K OLED touch panel with a stylus-ready hinge and full Thunderbolt 4 connectivity for everyday productivity and light creative work.',
    highlights: ['14" 3K OLED, 120Hz, touch + stylus support', 'Intel Core Ultra 9 185H', 'Thunderbolt 4 for fast docking and external displays'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/282fa6b1-5d9e-4950-ab46-1da2defbe6a3/',
    product_url: 'https://www.asus.com/us/laptops/for-home/zenbook/asus-zenbook-14-ux3405/',
    price_usd: 1399.99, // retailer-sourced estimate
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'Intel Arc Graphics (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 16,
    storage_gb: 1024,
    screen_size_in: 14,
    battery_hours: 14,
    weight_kg: 1.2,
    rating: 4.5,
    review_count: 96,
    in_stock: true,
    use_cases: ['productivity', 'creator', 'business'],
  },

  // ---- ProArt (creator / studio) ----
  {
    id: 'proart-px13-hn7306',
    name: 'ASUS ProArt PX13 (HN7306)',
    brand_line: 'proart',
    series: 'ProArt PX',
    category: 'ProArt PX',
    description: '"Your ultimate portable studio" — a 360° convertible creator laptop with 64GB of unified memory for unstoppable on-the-go AI and content work.',
    highlights: ['64GB unified memory — "Unstoppable AI"', '13.3" 3K OLED touchscreen, 360° convertible', 'AMD Ryzen AI Max+ 395, 16 cores'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/e94a421e-3a3b-4350-beb0-3215e70aa17a/',
    product_url: 'https://www.asus.com/us/laptops/for-creators/proart/proart-px13-hn7306/',
    price_usd: 2799,
    cpu: 'AMD Ryzen AI Max+ 395',
    gpu: 'AMD Radeon Graphics (unified)',
    gpu_tier: 'integrated',
    ram_gb: 64,
    storage_gb: 1024,
    screen_size_in: 13.3,
    battery_hours: 10,
    weight_kg: 1.39,
    rating: 4.7,
    review_count: 41,
    in_stock: true,
    use_cases: ['creator', 'professional'],
  },
  {
    id: 'proart-pz14-ht7407',
    name: 'ASUS ProArt PZ14 (HT7407)',
    brand_line: 'proart',
    series: 'ProArt PZ',
    category: 'ProArt PZ',
    description: '"Performance That Keeps You Creating" — a remarkably light detachable-tablet creator laptop with a brilliant 3K OLED display and ultra-smooth 144Hz motion.',
    highlights: ['14" 3K OLED touchscreen, 144Hz', 'Detachable tablet design, 0.79kg', 'Snapdragon X2 Elite (always-connected)'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/3724e2c3-d1c7-45a9-9d87-43d2db53b2dc/',
    product_url: 'https://www.asus.com/us/laptops/for-creators/proart/proart-pz14-ht7407/',
    price_usd: 2499,
    cpu: 'Qualcomm Snapdragon X2 Elite',
    gpu: 'Qualcomm Adreno (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 32,
    storage_gb: 1024,
    screen_size_in: 14,
    battery_hours: 14,
    weight_kg: 0.79,
    rating: 4.6,
    review_count: 19,
    in_stock: true,
    use_cases: ['creator', 'professional', 'travel'],
  },

  // ---- Vivobook (mainstream / everyday laptops) ----
  {
    id: 'vivobook-s14-m5406',
    name: 'ASUS Vivobook S14 (M5406)',
    brand_line: 'vivobook',
    series: 'Vivobook S',
    category: 'Vivobook S',
    description: '"Everyday, elevated" — a Copilot+ PC with a sleek minimalist design and a bright OLED display for school and work.',
    highlights: ['14" 3K OLED, 120Hz', 'Copilot+ PC AI features', 'AMD Ryzen AI 9 HX 370'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/496ec5ea-48e1-4c76-bbff-9f5de8368036/',
    product_url: 'https://www.asus.com/us/laptops/for-home/vivobook/',
    price_usd: 1199,
    cpu: 'AMD Ryzen AI 9 HX 370',
    gpu: 'AMD Radeon Graphics (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 16,
    storage_gb: 512,
    screen_size_in: 14,
    battery_hours: 12,
    weight_kg: 1.4,
    rating: 4.4,
    review_count: 87,
    in_stock: true,
    use_cases: ['student', 'productivity', 'business'],
  },
  {
    id: 'vivobook-pro-15-n6506-2024',
    name: 'ASUS Vivobook Pro 15 OLED (N6506)',
    brand_line: 'vivobook',
    series: 'Vivobook Pro',
    category: 'Vivobook Pro',
    description: 'A creator-leaning Vivobook that pairs a punchy 3K 120Hz OLED panel with discrete RTX graphics, Thunderbolt 4, and an SD card reader for photo/video work on a budget.',
    highlights: ['15.6" 3K 120Hz OLED', 'Up to Intel Core Ultra 9 + NVIDIA GeForce RTX 4060', 'Thunderbolt 4 and full-size SD card reader'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/6dcd7178-691d-4c0c-b3f4-d82f2c0ff8c6/',
    product_url: 'https://www.asus.com/laptops/for-home/vivobook/asus-vivobook-pro-15-oled-n6506/',
    price_usd: 1199.99, // estimated
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'NVIDIA GeForce RTX 4060',
    gpu_tier: 'entry',
    ram_gb: 16,
    storage_gb: 1024,
    screen_size_in: 15.6,
    battery_hours: 8,
    weight_kg: 1.8,
    rating: 4.3,
    review_count: 62,
    in_stock: true,
    use_cases: ['creator', 'student', 'productivity'],
  },
  {
    id: 'vivobook-go-15-e1504g-2024',
    name: 'ASUS Vivobook Go 15 (E1504G)',
    brand_line: 'vivobook',
    series: 'Vivobook Go',
    category: 'Vivobook Go',
    description: 'An everyday budget laptop for browsing, schoolwork, and documents — a durable MIL-STD-810H chassis around a simple, affordable Intel Processor N150 build.',
    highlights: ['15.6" FHD display', 'MIL-STD-810H durability testing at a budget price', 'Backlit keyboard with fingerprint login'],
    image_url: 'https://eshop.asus.com/media/catalog/product/v/i/vivobook_go_15_e1504f_e1504g_product_photo_1b_mixed_black_05_fingerprint_backlit.jpg',
    product_url: 'https://eshop.asus.com/us/21044-us-cnf-auto.html',
    price_usd: 299.99, // confirmed live price
    cpu: 'Intel Processor N150',
    gpu: 'Intel UHD Graphics (integrated)',
    gpu_tier: 'integrated',
    ram_gb: 4,
    storage_gb: 128,
    screen_size_in: 15.6,
    battery_hours: 10,
    weight_kg: 1.63,
    rating: 4.3,
    review_count: 112,
    in_stock: true,
    use_cases: ['student', 'budget', 'travel'],
  },
];

// Cross-sell / upsell accessories — separate from the laptop CATALOG so
// search-products/browse-products-by-series (which only ever browse
// laptops) don't accidentally surface a mouse or a monitor. Used by
// get-recommendations and addable to the cart like any laptop.
const ACCESSORIES = [
  {
    id: 'rog-gladius-iii-mouse',
    name: 'ROG Gladius III Wireless Mouse',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Gaming Mouse',
    description: 'Lightweight wireless gaming mouse with swappable switches and Aura Sync RGB.',
    highlights: ['79g ultralight design', 'Hot-swappable switches', '2.4GHz wireless + Bluetooth'],
    image_url: null,
    price_usd: 99,
    rating: 4.7,
    review_count: 340,
    in_stock: true,
    use_cases: ['gaming'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'asus-dual-usb-c-dock',
    name: 'ASUS Dual USB-C Docking Station',
    brand_line: 'zenbook',
    series: 'ASUS Accessories',
    category: 'Docking Station',
    description: 'One-cable 4K dual-monitor dock with 100W power delivery — ideal for ultraportables.',
    highlights: ['Dual 4K@60Hz output', '100W USB-C power delivery', 'Single-cable desk setup'],
    image_url: null,
    price_usd: 149,
    rating: 4.5,
    review_count: 212,
    in_stock: true,
    use_cases: ['productivity', 'business', 'creator'],
    compatible_brand_lines: ['zenbook', 'vivobook', 'proart'],
    is_accessory: true,
  },
  {
    id: 'asus-neoprene-sleeve-14',
    name: 'ASUS Neoprene Sleeve 14"',
    brand_line: 'zenbook',
    series: 'ASUS Accessories',
    category: 'Sleeve',
    description: 'Slim protective sleeve for 14-inch laptops, water-resistant neoprene.',
    highlights: ['Water-resistant exterior', 'Soft interior lining', 'Fits most 14" laptops'],
    image_url: null,
    price_usd: 29,
    rating: 4.4,
    review_count: 501,
    in_stock: true,
    use_cases: ['travel', 'student', 'productivity'],
    compatible_brand_lines: ['zenbook', 'vivobook'],
    is_accessory: true,
  },
  {
    id: 'rog-strix-xg27-monitor',
    name: 'ROG Strix XG27AQ 27" Gaming Monitor',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Monitor',
    description: '27" QHD 170Hz IPS gaming monitor with G-SYNC compatibility.',
    highlights: ['170Hz QHD IPS panel', 'G-SYNC Compatible', 'HDR400'],
    image_url: null,
    price_usd: 399,
    rating: 4.8,
    review_count: 150,
    in_stock: true,
    use_cases: ['gaming'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'proart-pa279-monitor',
    name: 'ProArt Display PA279CRV 27" 4K Monitor',
    brand_line: 'proart',
    series: 'ProArt Accessories',
    category: 'Monitor',
    description: 'Factory-calibrated 4K HDR monitor for color-critical creative work.',
    highlights: ['Factory color calibration', '4K UHD, 98% DCI-P3', 'Built-in colorimeter support'],
    image_url: null,
    price_usd: 599,
    rating: 4.8,
    review_count: 87,
    in_stock: true,
    use_cases: ['creator', 'professional'],
    compatible_brand_lines: ['proart', 'zenbook'],
    is_accessory: true,
  },
  {
    id: 'asus-portable-ssd-1tb',
    name: 'ASUS 1TB Portable SSD',
    brand_line: 'vivobook',
    series: 'ASUS Accessories',
    category: 'Storage',
    description: 'Pocket-sized 1TB USB-C SSD with up to 1050MB/s transfer speeds.',
    highlights: ['1050MB/s transfer speeds', 'Pocket-sized aluminum body', 'USB-C, backward compatible'],
    image_url: null,
    price_usd: 89,
    rating: 4.6,
    review_count: 275,
    in_stock: true,
    use_cases: ['creator', 'student', 'productivity', 'gaming'],
    compatible_brand_lines: ['zenbook', 'rog', 'tuf', 'vivobook', 'proart'],
    is_accessory: true,
  },
  {
    id: 'rog-strix-scope-ii-keyboard',
    name: 'ROG Strix Scope II 96 Wireless',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Gaming Keyboard',
    description: 'A tri-mode 96%-layout mechanical keyboard with hot-swappable switches, built for gamers who don\'t want to give up a numpad.',
    highlights: ['Tri-mode connectivity: Bluetooth, 2.4GHz wireless, USB-C wired', 'Hot-swappable switch sockets', 'Compact 96% layout with dedicated media controls'],
    image_url: 'https://eshop.asus.com/media/catalog/product/b/c/bcfec7610ca8a77f9cedcf24cfbda6d6.png',
    product_url: 'https://eshop.asus.com/us/90mp037a-bkaa01-rog-strix-scope-ii-96-wireless.html',
    price_usd: 149.99,
    rating: 4.6,
    review_count: 118,
    in_stock: true,
    use_cases: ['gaming'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'rog-cetra-true-wireless',
    name: 'ROG Cetra True Wireless',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Headset',
    description: 'True wireless gaming earbuds with active noise cancellation and a dedicated low-latency mode for fast-paced games.',
    highlights: ['Active Noise Cancellation (ANC)', 'Low-latency gaming mode', 'Compact charging case with onboard controls'],
    image_url: null,
    product_url: 'https://shop.asus.com/us/90yh03x1-b5ua00-rog-cetra-true-wireless.html',
    price_usd: 99.99,
    rating: 4.4,
    review_count: 65,
    in_stock: true,
    use_cases: ['gaming'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'asus-webcam-c3',
    name: 'ASUS Webcam C3',
    brand_line: 'zenbook',
    series: 'ASUS Accessories',
    category: 'Webcam',
    description: 'A 1080p30 USB webcam with beamforming dual microphones and 360° rotation — an easy upgrade for video calls on any laptop.',
    highlights: ['1080p30 video with beamforming dual mic', '360° rotation for flexible framing', 'Plug-and-play USB-A/USB-C'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/818d26a5-2d8b-49e3-8381-86fb5945d8cd/w184',
    product_url: 'https://www.asus.com/us/accessories/streaming-kits/all-series/asus-webcam-c3/',
    price_usd: 59.99, // estimated
    rating: 4.5,
    review_count: 210,
    in_stock: true,
    use_cases: ['productivity', 'business', 'creator', 'student'],
    compatible_brand_lines: ['zenbook', 'rog', 'tuf', 'vivobook', 'proart'],
    is_accessory: true,
  },
  {
    id: 'rog-ranger-bp2800-backpack',
    name: 'ROG Ranger BP2800',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Backpack',
    description: 'A rugged gaming backpack that fits laptops up to 18" with a water-repellent exterior, built to protect a full-size ROG rig on the go.',
    highlights: ['Fits laptops up to 18"', 'Water-repellent exterior fabric', 'Dedicated padded laptop and gear compartments'],
    image_url: 'https://eshop.asus.com/media/catalog/product/b/d/bd84c18dd5ca2f264b6c0a5aa4a9338b.png',
    product_url: 'https://eshop.asus.com/us/90xb0a30-bbp000-rog-ranger-bp2800-gaming-backpack.html',
    price_usd: 99.99,
    rating: 4.6,
    review_count: 88,
    in_stock: true,
    use_cases: ['gaming', 'travel'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'asus-dual-4k-dock-dc201',
    name: 'ASUS Dual 4K USB-C Dock DC201',
    brand_line: 'zenbook',
    series: 'ASUS Accessories',
    category: 'Docking Station',
    description: 'A 5-in-1 USB-C dock that drives dual 4K60 displays over HDMI 2.1 and USB-C, with 100W power delivery to keep your laptop charged while docked.',
    highlights: ['Dual 4K@60Hz output (HDMI 2.1 + USB-C)', '100W USB-C power delivery passthrough', 'Compact 5-in-1 port design'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/f98e7bc2-2635-41ef-9d6d-0ab08f46204f/w184',
    product_url: 'https://shop.asus.com/us/90xb094n-bds000-asus-dual-4k-usb-c-dock-dc201.html',
    price_usd: 139.99,
    rating: 4.5,
    review_count: 145,
    in_stock: true,
    use_cases: ['productivity', 'business', 'creator'],
    compatible_brand_lines: ['zenbook', 'rog', 'tuf', 'vivobook', 'proart'],
    is_accessory: true,
  },
  {
    id: 'rog-harpe-ace-mouse',
    name: 'ROG Harpe Ace Aim Lab Edition',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Gaming Mouse',
    description: 'A 54g ultralight esports mouse co-developed with Aim Lab, with a 36000 DPI sensor and tri-mode connectivity for tournament-grade precision.',
    highlights: ['54g ultralight shell', '36000 DPI optical sensor', 'Tri-mode connectivity: 2.4GHz wireless, Bluetooth, wired'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/0F9B888C-4649-4829-B3C9-BDD8734907A4',
    product_url: 'https://rog.asus.com/us/mice-mouse-pads/mice/wireless/rog-harpe-ace-aim-lab-edition-model/spec/',
    price_usd: 79.99, // promo price; list price $149.99
    rating: 4.7,
    review_count: 205,
    in_stock: true,
    use_cases: ['gaming'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'rog-scabbard-ii-mousepad',
    name: 'ROG Scabbard II Medium',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Mousepad',
    description: 'A medium gaming mousepad with a nano-coating surface that repels water, oil, and dust for consistent tracking over time.',
    highlights: ['Nano-coating: water, oil, and dust repellent', 'Smooth, consistent-glide surface', 'Non-slip rubber base'],
    image_url: 'https://eshop.asus.com/media/catalog/product/r/o/rog_scabbard_ii_medium_size_01_1.jpg',
    product_url: 'https://eshop.asus.com/us/90mp02h0-bpua00-rog-scabbard-ii.html',
    price_usd: 39.99,
    rating: 4.5,
    review_count: 96,
    in_stock: true,
    use_cases: ['gaming'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'rog-swift-oled-pg27aqdm',
    name: 'ROG Swift OLED PG27AQDM-R',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Monitor',
    description: 'A 26.5" QHD WOLED gaming monitor with a blistering 240Hz refresh rate, 0.03ms response time, and 1000-nit HDR peak brightness.',
    highlights: ['26.5" QHD WOLED, 240Hz, 0.03ms response', '1000-nit peak HDR brightness', 'Excellent color accuracy for both gaming and content viewing'],
    image_url: 'https://eshop.asus.com/media/catalog/product/8/4/84646ffcb7d811f6bf614f736f86c8e5.png',
    product_url: 'https://eshop.asus.com/us/90lm08q0-b02ab0-rog-swift-oled-pg27aqdm-r.html',
    price_usd: 699,
    rating: 4.8,
    review_count: 310,
    in_stock: true,
    use_cases: ['gaming', 'creator'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'rog-swift-360hz-pg27aqn',
    name: 'ROG Swift 360Hz PG27AQN',
    brand_line: 'rog',
    series: 'ROG Accessories',
    category: 'Monitor',
    description: 'A 27" QHD Fast IPS monitor built for competitive esports, with a 360Hz refresh rate, 1ms response, and a dedicated NVIDIA G-SYNC processor.',
    highlights: ['27" QHD Fast IPS, 360Hz, 1ms response', 'Dedicated NVIDIA G-SYNC processor', 'Tuned for competitive, high-frame-rate esports titles'],
    image_url: 'https://eshop.asus.com/media/catalog/product/6/7/67fa815ff31cd1dec7f4f203c8e74e02.png',
    product_url: 'https://eshop.asus.com/us/90lm0820-b013b0-rog-swift-360hz-pg27aqn.html',
    price_usd: 649,
    rating: 4.7,
    review_count: 178,
    in_stock: true,
    use_cases: ['gaming'],
    compatible_brand_lines: ['rog', 'tuf'],
    is_accessory: true,
  },
  {
    id: 'asus-va24ehf-monitor',
    name: 'ASUS VA24EHF',
    brand_line: 'vivobook',
    series: 'ASUS Accessories',
    category: 'Monitor',
    description: 'An affordable 23.8" FHD IPS monitor with a 100Hz refresh rate and Adaptive-Sync — a solid general-purpose second display for any laptop.',
    highlights: ['23.8" FHD IPS, 100Hz refresh rate', 'Adaptive-Sync for smoother motion', 'Eye Care flicker-free, low blue-light panel'],
    image_url: 'https://dlcdnwebimgs.asus.com/gain/fe13f77e-8e97-48f1-a810-8c73ac2bbf5e/w692',
    product_url: 'https://www.asus.com/us/displays-desktops/monitors/eye-care/va24ehf/',
    price_usd: 119.99,
    rating: 4.5,
    review_count: 395,
    in_stock: true,
    use_cases: ['productivity', 'business', 'student'],
    compatible_brand_lines: ['zenbook', 'rog', 'tuf', 'vivobook', 'proart'],
    is_accessory: true,
  },
  {
    id: 'proart-pa278cv-monitor',
    name: 'ProArt Display PA278CV',
    brand_line: 'proart',
    series: 'ProArt Accessories',
    category: 'Monitor',
    description: 'A 27" QHD IPS monitor that\'s Calman Verified with 100% sRGB coverage and 65W USB-C power delivery — a compact, color-accurate display for creative work.',
    highlights: ['27" QHD IPS, 100% sRGB, Calman Verified', '65W USB-C power delivery — charge your laptop over one cable', 'Factory color calibration report included'],
    image_url: 'https://eshop.asus.com/media/catalog/product/0/_/0._asus_pa278cv_-_product_image-m.jpg',
    product_url: 'https://eshop.asus.com/ca-en/90lm06q1-b013c1-proart-display-pa278cv.html',
    price_usd: 329, // estimated USD; confirmed $399 CAD at research time
    rating: 4.7,
    review_count: 134,
    in_stock: true,
    use_cases: ['creator', 'professional'],
    compatible_brand_lines: ['proart', 'zenbook'],
    is_accessory: true,
  },
];

// Combined index used for lookups (get-product-details, manage-cart,
// compare-products, get-recommendations) so accessories are addressable
// the same way laptops are. Laptop-only browsing (search-products,
// browse-products-by-series) intentionally keeps using CATALOG alone.
const ALL_ITEMS = [...CATALOG, ...ACCESSORIES];

// ---- ASUS Premium Care (APC) warranty add-ons ----
// Real ASUS protection-plan program, sold as "ASUS Premium Care" (APC),
// with an add-on called "Accidental Damage Protection" (ADP). Pricing:
//   - apc-3yr-adp: $209.99 is CONFIRMED — this is shop.asus.com's live
//     price for the "3 Years of Coverage" warranty SKU (which bundles ADP)
//     as of the July 2026 research pass.
//   - apc-1yr / apc-2yr: $79.99 / $149.99 are REASONABLE ESTIMATES, scaled
//     down from the confirmed 3-year anchor above — not scraped from a
//     live SKU. Replace with confirmed per-tier pricing if/when ASUS
//     publishes it.
// A plan attaches to a specific cart line item via `for_product_id` — see
// lib/cart.js `addWarrantyItem` and actions/manage-cart/index.js.
const WARRANTY_PLANS = [
  {
    id: 'apc-1yr',
    name: 'ASUS Premium Care — 1-Year Extension',
    provider: 'ASUS Premium Care (APC)',
    duration_years: 1,
    price_usd: 79.99, // estimate — see pricing note above
    includes_adp: false,
    covers: ['Warranty extension only (no accidental damage)'],
    description: 'Extends ASUS\'s standard warranty on this laptop by 1 year. Does not cover accidental damage.',
  },
  {
    id: 'apc-2yr',
    name: 'ASUS Premium Care — 2-Year Extension',
    provider: 'ASUS Premium Care (APC)',
    duration_years: 2,
    price_usd: 149.99, // estimate — see pricing note above
    includes_adp: false,
    covers: ['Warranty extension only (no accidental damage)'],
    description: 'Extends ASUS\'s standard warranty on this laptop by 2 years. Does not cover accidental damage.',
  },
  {
    id: 'apc-3yr-adp',
    name: 'ASUS Premium Care — 3-Year Extension + Accidental Damage Protection (ADP)',
    provider: 'ASUS Premium Care (APC)',
    duration_years: 3,
    price_usd: 209.99, // confirmed — shop.asus.com "3 Years of Coverage" SKU, live price at last refresh
    includes_adp: true,
    covers: ['Warranty extension', 'Accidental Damage Protection (ADP): drops, spills, electrical surges, cracked LCD'],
    description: 'Extends ASUS\'s standard warranty on this laptop by 3 years and adds Accidental Damage Protection (ADP) for drops, spills, electrical surges, and cracked LCD screens.',
  },
];

/**
 * Fallback color swatch per brand line, used by widgets when a product has
 * no image_url. Kept here (not just in the EDS repo) so the structuredContent
 * payload can optionally carry it for hosts that don't run the EDS widget.
 */
const BRAND_FALLBACK_COLOR = {
  zenbook: '#1F3A5C',
  rog: '#E2231A',
  tuf: '#F2A900',
  vivobook: '#7B2FF7',
  proart: '#C9A227',
};

/**
 * Returns a deep link to the real ASUS product page when we have one
 * (`product_url`, populated for every laptop in CATALOG from the July 2026
 * research pass); accessories and any future item without a confirmed real
 * URL fall back to an asus.com search link.
 */
function buyUrl(product) {
  if (product.product_url) return product.product_url;
  return `https://www.asus.com/search/?q=${encodeURIComponent(product.name)}`;
}

/** Trims a catalog record down to the fields widgets actually render. */
function toCard(product) {
  return {
    id: product.id,
    name: product.name,
    description: product.description,
    image_url: product.image_url,
    category: product.category,
    brand_line: product.brand_line,
    series: product.series,
    price_usd: product.price_usd,
    cpu: product.cpu,
    gpu: product.gpu,
    gpu_tier: product.gpu_tier,
    ram_gb: product.ram_gb,
    storage_gb: product.storage_gb,
    screen_size_in: product.screen_size_in,
    weight_kg: product.weight_kg,
    battery_hours: product.battery_hours,
    rating: product.rating,
    review_count: product.review_count,
    in_stock: product.in_stock,
    use_cases: product.use_cases,
    highlights: product.highlights,
    fallback_color: BRAND_FALLBACK_COLOR[product.brand_line] || '#1a1a1a',
    buy_url: buyUrl(product),
    is_accessory: !!product.is_accessory,
  };
}

/**
 * Resolves a single product OR accessory by id (exact) or name (exact,
 * then partial). Used by get-product-details, compare-products, the cart
 * actions, and get-recommendations.
 */
function resolveProduct({ product_id, product_name } = {}) {
  if (product_id) {
    const byId = ALL_ITEMS.find((p) => p.id === product_id);
    if (byId) return byId;
  }
  if (product_name && typeof product_name === 'string' && product_name.trim()) {
    const query = product_name.trim().toLowerCase();
    const exact = ALL_ITEMS.find((p) => p.name.toLowerCase() === query);
    if (exact) return exact;
    const partial = ALL_ITEMS.find((p) => p.name.toLowerCase().includes(query));
    if (partial) return partial;
  }
  return null;
}

/**
 * Resolves an ASUS Premium Care warranty plan by id (exact) or name (exact,
 * then partial). Used by get-warranty-options and manage-cart.
 */
function resolveWarrantyPlan({ plan_id, plan_name } = {}) {
  if (plan_id) {
    const byId = WARRANTY_PLANS.find((p) => p.id === plan_id);
    if (byId) return byId;
  }
  if (plan_name && typeof plan_name === 'string' && plan_name.trim()) {
    const query = plan_name.trim().toLowerCase();
    const exact = WARRANTY_PLANS.find((p) => p.name.toLowerCase() === query);
    if (exact) return exact;
    const partial = WARRANTY_PLANS.find((p) => p.name.toLowerCase().includes(query));
    if (partial) return partial;
  }
  return null;
}

module.exports = {
  CATALOG,
  ACCESSORIES,
  ALL_ITEMS,
  GPU_TIERS,
  WARRANTY_PLANS,
  BRAND_FALLBACK_COLOR,
  toCard,
  resolveProduct,
  resolveWarrantyPlan,
  buyUrl,
};
